# TRIAXUS Visualization System Configuration
# This file contains all configurable parameters for the TRIAXUS system
# Modify this file to change system behavior without editing Python code

# System-wide settings
system:
  name: "TRIAXUS Visualization System"
  version: "1.0.0"
  debug: false
  log_level: "INFO"

# Plot dimensions and layout
plot:
  default_width: 800
  default_height: 600
  min_width: 400
  min_height: 300
  max_width: 2000
  max_height: 1500
  
  # Line configurations
  line:
    default_width: 2
    min_width: 1
    max_width: 10
    
  # Marker configurations
  marker:
    default_size: 4
    min_size: 1
    max_size: 20
    
  # Grid configurations
  grid:
    width: 1
    color: "lightgray"
    show: true

# Color schemes for different themes
colors:
  themes:
    default:
      background: "#FFFFFF"
      grid: "#E0E0E0"
      text: "#333333"
      primary: "#1976D2"
      secondary: "#D32F2F"
      accent: "#43A047"
      
    oceanographic:
      background: "#FAFAFA"
      grid: "#B0C4DE"
      text: "#2F4F4F"
      primary: "#1976D2"
      secondary: "#D32F2F"
      accent: "#43A047"
      
    dark:
      background: "#2C3E50"
      grid: "#34495E"
      text: "#ECF0F1"
      primary: "#E74C3C"
      secondary: "#3498DB"
      accent: "#2ECC71"
      
    high_contrast:
      background: "#FFFFFF"
      grid: "#000000"
      text: "#000000"
      primary: "#FF0000"
      secondary: "#0000FF"
      accent: "#00FF00"

# Variable-specific colors
variables:
  tv290C:
    default: "#FF6B6B"
    oceanographic: "#B73E3A"
    dark: "#FF6B6B"
    high_contrast: "#FF0000"
    
  flECO-AFL:
    default: "#4ECDC4"
    oceanographic: "#1E88E5"
    dark: "#4ECDC4"
    high_contrast: "#00FF00"
    
  ph:
    default: "#45B7D1"
    oceanographic: "#43A047"
    dark: "#45B7D1"
    high_contrast: "#0000FF"
    
  sbeox0Mm_L:
    default: "#96CEB4"
    oceanographic: "#7CB342"
    dark: "#96CEB4"
    high_contrast: "#FFFF00"
    
  sal00:
    default: "#FFEAA7"
    oceanographic: "#8E24AA"
    dark: "#FFEAA7"
    high_contrast: "#FF00FF"

# Mapbox configurations
mapbox:
  token: "pk.eyJ1Ijoic3RldmVubGkzNjUiLCJhIjoiY21mODh5ZWljMDYzZDJtcGl1NnFsYzM0NCJ9.vCkXjWG4yP7uRKn3AQekLg"  # Mapbox token
  style: "satellite-streets"  # Default Mapbox style
  # Offline mode: when token is empty, use OpenStreetMap
  offline_mode: false  # Set to true for offline usage

# Map configurations
map:
  # Default map style
  default_style: "satellite-streets"
  available_styles:
    # Mapbox styles (require token)
    - "satellite-streets"
    - "satellite"
    - "streets"
    - "outdoors"
    - "light"
    - "dark"
    - "basic"
    - "hybrid"
    # Offline style (no token required)
    - "open-street-map"
  
  # Map dimensions
  width: 800
  height: 600
  
  # Map padding and zoom
  padding: 0.2
  zoom:
    auto_zoom:
      very_wide: 2.0
      wide: 1.0
      medium: 0.5
      small: 0.2
    levels:
      very_wide: 6
      wide: 8
      medium: 10
      small: 12
      very_small: 14
  
  # Map projection (for scattergeo)
  projection: "equirectangular"
  
  # Map colors
  colors:
    land: "lightgray"
    ocean: "lightblue"
    lakes: "lightblue"
    rivers: "lightblue"
  
  # Trajectory line styling
  line:
    width: 3
    color: "#D32F2F"  # Red for trajectory
    
  # Marker styling
  marker:
    size: 8
    opacity: 0.8
    start_color: "#43A047"  # Green for start
    end_color: "#D32F2F"    # Red for end
    current_color: "#1976D2" # Blue for data points
    start_size: 12
    end_size: 12
    
  # Zoom configuration
  zoom:
    default: 10
    min: 1
    max: 20
    # Auto-zoom thresholds based on data span (in degrees)
    auto_zoom:
      very_wide: 2.0    # > 2.0 degrees -> zoom level 6
      wide: 1.0         # > 1.0 degrees -> zoom level 8
      medium: 0.5       # > 0.5 degrees -> zoom level 10
      small: 0.2        # > 0.2 degrees -> zoom level 12
      very_small: 0.0   # <= 0.2 degrees -> zoom level 14
  
  # View padding (percentage of data range)
  padding: 0.2  # 20% padding around data bounds
  
  # Layout margins
  margin:
    left: 0
    right: 0
    top: 60
    bottom: 0

# Font configurations
font:
  family: "Arial, sans-serif"
  size: 12
  title_size: 14
  annotation_size: 10
  status_size: 12

# Annotation configurations
annotations:
  font_size: 10
  color: "gray"
  border_width: 1
  border_color: "black"
  background_color: "white"
  opacity: 0.8

# Status display configurations
status:
  font_size: 12
  border_width: 2
  colors:
    success: "#4CAF50"
    warning: "#FF9800"
    error: "#F44336"
    info: "#2196F3"

# Data processing configurations
data:
  # Sampling configurations
  sampling:
    default_size: 1000
    min_size: 100
    max_size: 10000
    random_seed: 42
    
  # Test data generation
  test_data:
    default_hours: 2
    default_points: 120
    default_pattern: "realistic"
    random_seed: 42
    depth_range: [0, 1000]
    lat_range: [-90, 90]
    lon_range: [-180, 180]
    
  # Data validation
  validation:
    level: "moderate"  # strict, moderate, lenient
    error_action: "warn"  # error, warn, ignore
    log_errors: true
    max_errors: 100

# File I/O configurations
files:
  default_format: "csv"
  encoding: "utf-8"
  delimiter: ","
  header: 0
  index_col: null
  parse_dates: ["time"]
  date_format: "%Y-%m-%d %H:%M:%S"

# Performance configurations
performance:
  max_data_points: 10000
  enable_caching: true
  cache_size: 100
  parallel_processing: false
  max_workers: 4

# Data generation configurations
data_generation:
  # Default parameters for test data generation
  default_duration_hours: 2.0
  default_points_per_hour: 60
  quick_points_per_hour: 30
  daily_points_per_hour: 10
  
  # Random seed for reproducible data
  random_seed: 42
  
  # Default locations for trajectory data
  locations:
    australia:
      start_lat: -16.9
      start_lon: 145.8
      description: "Near Cairns, Great Barrier Reef"
    default:
      start_lat: 35.0
      start_lon: -120.0
      description: "Default location"
  
  # Oceanographic parameter ranges
  oceanographic_ranges:
    temperature: [0, 30]  # Celsius
    salinity: [30, 40]    # PSU
    ph: [7.5, 8.5]        # pH units
    oxygen: [0, 15]       # mg/L
    fluorescence: [0, 2]  # Relative units
    depth: [0, 200]       # meters for typical profiles
  
  # Default oceanographic values
  default_values:
    temperature: 15.0
    salinity: 35.0
    ph: 8.1
    oxygen: 8.0
    fluorescence: 0.5
  
  # Noise levels for realistic data
  noise_levels:
    low: 0.01
    medium: 0.05
    high: 0.1
  
  # Amplitude factors for data variation
  amplitude_factors:
    temperature: 4.0
    salinity: 1.5
    oxygen: 2.0
    fluorescence: 0.3
    ph: 0.2

# Data sampling configurations
data_sampling:
  # Default sample sizes
  default_sample_size: 1000
  large_sample_size: 2000
  very_large_sample_size: 5000
  huge_sample_size: 10000
  
  # Random seed for reproducible sampling
  random_seed: 42
  
  # Depth intervals for stratified sampling
  depth_intervals:
    - [0, 50]
    - [50, 100]
    - [100, 200]
  
  # Time intervals for time-based sampling
  time_intervals:
    hourly: "1H"
    daily: "1D"
    minute: "1min"

# Statistical constants
statistics:
  # Outlier detection parameters
  outlier_detection:
    iqr_multiplier: 1.5
    zscore_threshold: 3.0
  
  # Quantile definitions
  quantiles:
    q25: 0.25
    q75: 0.75

# Depth zone definitions
depth_zones:
  - [0, 200, "Epipelagic", "rgba(0,255,0,0.1)"]
  - [200, 1000, "Mesopelagic", "rgba(0,0,255,0.1)"]
  - [1000, 4000, "Bathypelagic", "rgba(128,0,128,0.1)"]
  - [4000, 6000, "Abyssopelagic", "rgba(0,0,0,0.1)"]
